"""Initial DB

Revision ID: de698966a650
Revises: 3f120ae55803
Create Date: 2022-09-07 03:29:11.253643

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "de698966a650"
down_revision = "3f120ae55803"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
    # ### end Alembic commands ###
